### ISSUE TITLE
Minor To-Do's

### ISSUE THREAD

**Issue by rene78** [rene78/PopComPics#6]
- [x] app-stats: decode username, e.g. Robert%20(Bic)%20Bicknell (only an issue on Chrome for Android). Closed with https://github.com/rene78/PopComPics/commit/6b28421eac052e971207956bd3f39d9349233da8
- [ ] Change scroll bar to something like in [latest-changes](https://github.com/rene78/latest-changes/blob/c79cfbd39be38f80a59a06f11fc5685dc29bf2d7/css/site.css#L143)
- [ ] Move svg's into img folder, like done with [My Cryptoportfolio](https://github.com/rene78/My-Cryptoportfolio/blob/master/img/icons.svg)
